### PR TITLE
simplify the logging subsystem

### PR DESCRIPTION
**Pull request by nicboul**

### CODE REVIEW

**Review by si74 — COMMENTED** [review]
looks much cleaner! only question is re: what the difference is btw log_warnx vs. log_warn - both seem to be printf'ing a list of items to stderr...

**Comment by nicboul** [comment]
The difference is that log_warn() also print the string corresponding to the value of errno: strerror(errno). Some function of the libc will store their error value in the globally accessible "errno" variable if an error happened to report what went wrong exactly. http://man7.org/linux/man-pages/man3/errno.3.html - So for these functions like read(), if the return code is != 0, we print the error with log_warn() instead of log_warnx(). And the reason to use "warn" and "warnx" convention is derived from https://linux.die.net/man/3/warnx

**Comment by nicboul** [comment]
Also they both fprintf() to stderr _only_ if there is no callback configured. Otherwise they pass the string to a callback, and the function called can decide where to output the message, like writing it in the GUI.

**Review by si74 — APPROVED** [review]
gotcha! thanks for the explanation 👍

**Pull request merged**
